services:
  postgres:
    image: postgres:16
    container_name: messaging-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: automatch_messaging
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  messaging-service:
    build: .
    container_name: messaging-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/automatch_messaging
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  pgdata: